# 根据实际情况修改配置信息
sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password:
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: {阿里云access-key-id}
    access-key-secret: {阿里云access-key-secret}
    bucket-name: {阿里云bucket-name }